name: OcbModExample

on:
  create:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  push:
    branches:
      - master
      - develop
      - main

jobs:

  compile:
    runs-on: windows-latest
    name: Windows MSVC build

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Call OCB-CS2 compiler action
      uses: OCB-CS2/OcbModCompiler@main
      with:
        name: "OcbModExample"
        version: "${{ github.ref_name }}"
        token: "${{ secrets.GITHUB_TOKEN }}"
        OCBTOKEN: "${{ secrets.OCBTOKEN }}"
        release: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
